### ISSUE TITLE
More Question, Less Issue

### ISSUE THREAD

**Issue by forrestrose** [natekspencer/hacs-vivint#154]
### The problem

Is there any way to connect to the cameras via network without enrolling them into Vivint panel?

### What version of Home Assistant Core are you running?

Core

**Comment by natekspencer** [comment]
Not that I'm aware of. You can connect some of them to your local network though without going directly through the panel's WiFi, but it still has to be registered with the panel.

It's been a while since I've done so (and I no longer have Vivint WiFi cameras), but to get it on your local network, you have to play around with the timing of getting your camera in setup mode, pressing the WPS button on your router, and then enrolling the camera through the Vivint panel.
