### ISSUE TITLE
Does this integration work with all Vivint panels?

### ISSUE THREAD

**Issue by ksignorini** [natekspencer/hacs-vivint#29]
Vivint is going to replace my current white SkyControl panel with a new, upgraded one. 

Will this integration work with the new panel?

Will I have to create a new integration?

Will I have to modify my existing Lovelace dashboard cards to point to new entities?

(FYI: Sorry to use issues to ask questions, but I cannot find any other support channels for your integration like a github forum. Do you have a Discord channel or is this the best means?)

**Comment by natekspencer** [comment]
> Will this integration work with the new panel?

The only panels this doesn't work with are the older Go! Control panels. It works with the Sky Control, which you currently have, and the Smart Hub which is what you'll be getting I'm guessing. Basically, as long as you login with the current Vivint app and not the Vivint Classic app, and not some yet released newer app, this integration _should_ work.

> Will I have to create a new integration?

You shouldn't need to as long as your username/password stay the same. I've tried to account for devices being added/removed from the panel to appear/delete automatically. But I can't say I've been able to test adding/removing a panel and the associated devices itself. Best case scenario is that the old devices, including the panel, disappear automatically and as the new panel and devices are added, they start to appear. Though the tech may add/transfer all your devices from the previous panel to the new one before it's associated with your account. I also don't know if the same messages are sent via the API when a new panel is added, so you may need to restart HA before the new panel and devices show up. Worst case scenario is deleting/re-adding the integration, but that should be relatively straight forward as well. I'd be interested in hearing back after the install is complete on what actually happened and what steps you needed to take.

> Will I have to modify my existing Lovelace dashboard cards to point to new entities?

Possibly, it depends on what happens from above and if the devices are named exactly the same when they are added to the new panel. If the devices don't get deleted automatically before new devices show up (and if they are named exactly the same), then you will end up with new entities with a number at the end, such as `binary_sensor.front_door_2`. If devices are automatically deleted first, then you should be ok. Otherwise, on a HA reboot, old devices _should_ get deleted and then you would just have to go into the integration and rename any entity that has an _# behind it. Or alternatively if you have a lot of devices, delete/re-install this integration.

> (FYI: Sorry to use issues to ask questions, but I cannot find any other support channels for your integration like a github forum. Do you have a Discord channel or is this the best means?)

Currently, this is the best means of asking questions.

**Comment by ksignorini** [comment]
Thanks for the answer. It will be a Smart Hub version says the tech. We'll be adding a few sensors as well.

I appreciate your work on this integration. It's made all the difference!
