### ISSUE TITLE
Camera feeds pretty lousy...can anything be done?

### ISSUE THREAD

**Issue by ksignorini** [natekspencer/hacs-vivint#30]
I'm wondering if anything can be done to improve the reliability and the speed of the camera entities and RTSP feeds from the Vivint system into HA?

At least for me, I can't count on the cameras/feeds staying stable and being available any time I want to see them; and when I do, they're usually incredibly slow and choppy.

Thanks.

**Comment by natekspencer** [comment]
This integration provides the rtsp url and an HD/SD and direct/internal/external option to HA. Outside of that, it relies on the stream and ffmpeg components in HA. To help reduce bandwidth/resource/network requirements, you should set these to SD and direct if you're having issues. I'm unaware of any other options at this moment that I can set to help with this. I've been watching the HA WebRTC a little bit, which should help whilst providing additional benefits, but I'm not sure on the timeline for that actually being available to custom components or how to implement it if it is at this time.

There's a lot of variables outside of this that effect your cameras rtsp responsiveness including, but not limited to: hardware running HA, your home network setup, how the Vivint cameras are setup to the panel and how the panel is setup on your network.

Frankly, the Wi-Fi and wired connection speeds in the Vivint panel are awful from my experience. Plugging your device in with an Ethernet cord should help. And then setting your cameras up so that they are on your network, rather than on the Vivint panels network, should provide an even better experience since that allows direct access to the rtsp stream, depending on the camera.

**Comment by ksignorini** [comment]
> And then setting your cameras up so that they are on your network, rather than on the Vivint panels network, should provide an even better experience since that allows direct access to the rtsp stream, depending on the camera.

Interesting. Is this easily done with Vivint cams/panels? I was under the impression that the cams had to sit on this 172. whatever network they put them on during install. (Is it a separate radio/interface in the panel?)

**Comment by natekspencer** [comment]
It's unfortunately not a super easy process. And it's a bit of trial and error. I can't remember the exact process since it's been a while since I've done so, but it goes something like this:
1. Remove camera from panel and factory reset the camera
2. Initiate WPS on camera and on your router
3. Click on "Add camera" from panel
4. Hope that camera connected to your network and that the panel sees a camera and adds it to the list of devices

**Comment by garettharnish** [comment]
I did it a bit differently.  I removed their PoE wifi bridge and ran a cable that connected the camera into my PoE switch (which my panel is also wired directly to).  It worked; the panel even detected the change in IP without having to remove and add the camera or factory reset it.
