### ISSUE TITLE
Adds Vivint hue lights to HA when they are already added

### ISSUE THREAD

**Issue by tmilsom** [natekspencer/hacs-vivint#49]
Could you add an option NOT to add the vivint lights added in the panel.

I have HUE added to the vivint panel for alarm lights but it creates a second light element for every bulb due to me directly having hue hub added. 

Thankyou for such a great addon!

**Comment by natekspencer** [comment]
Glad it's been useful. The easiest option is probably to just disable those extra hue devices from the Vivint integration that you don't need. If there were a way in the Vivint API that signaled it was a hue device, I'd consider an option to not include those, but since they all look like regular lights, I'd rather not exclude an entire domain for this use case.
